jinsol.md

jinsol.md 파일 새로 생성했습니다. 확인 부탁드려요

[jinsol] : test파일 생성

---

hello_jinsol.md

[jinsol] : hello_jinsol.md 파일 작성

---

111.md

commit test

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/MainActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/notifications/NotificationsFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_main.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml
Application/Project_Footprint/app/src/main/res/layout/test.xml
Web/Project_Footprint/.idea/workspace.xml

- MainActivity.kt : 토글 스위치 ON/OFF에 따라 서비스 온오프 구했습니다.
- ForegroundService.kt : 스위치가 ON되면 실행되는 동작을 기술했습니다. (Foreground에서 앱 실행 시작)

[HyeonJun] ForegroundService 구현

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/HomeActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/MainActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeViewModel.kt
Application/Project_Footprint/app/src/main/res/layout/activity_main.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml

- HomeFragment.kt : 기존 MainActivity.kt의 동작을 옮겼습니다. (정상 작동 확인)
- MainActivity.kt : 더이상 사용하지 않습니다.

[HyeonJun] HomeFragment 구현

---

Web/Project_Footprint/website/models.py

- website/models.py : history 모델 누락되어서 추가했습니다.

[YulHee] History Model  누락되어서 추가했습니다.

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/templates/place_list.html
Web/Project_Footprint/website/templates/place_register.html
Web/Project_Footprint/website/urls.py
Web/Project_Footprint/website/views.py

- forms.py : Place를 정보 입력을 받아 등록할 수 있도록 구현했습니다.
- urls.py : place_register 경로를 추가해줬습니다.
- views.py : 값을 입력 받아 Place 모델을 생성하도록 구현했습니다.
- temlpates/place_register.html : PlaceRegisterForm을 이용하여 Place를 등록할 수 있도록 하는 페이지를 간단하게 구현했습니다.
- temlpates/place_list.html : place 변수명을 places로 변경하였습니다.

[yewon] Place Register form 구현했습니다.

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/place_list.html
Web/Project_Footprint/website/templates/place_restaurant_list.html
Web/Project_Footprint/website/templates/place_search.html
Web/Project_Footprint/website/templates/place_sights_list.html
Web/Project_Footprint/website/urls.py
Web/Project_Footprint/website/views.py

- urls.py : place_search에 필요한 url을 추가하고 index링크에 해당하는 url을 추가하였습니다.
- views.py : place_search 값을 이용하여 list로 출력할수 있도록 구현했습니다.
- place_search.html : place_search 한 값을 이용하여 검색 후 출력 페이지를 간단하게 구현했습니다.
- place_restaurant_list.html, place_sights_list.html : restaurant와 sights 구분하여 보여주는 page를 구현했습니다.
- base.html : 검색 툴을 추가하고 링크 url을 수정하였습니다.

[yewon] Place Search 기능 구현했습니다.

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/MainActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/NotifyPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Place.kt
Application/Project_Footprint/app/src/main/res/layout/item.xml

- ForegroundService.kt : 주기적으로 갱신되는 비콘 리스트를 리턴하는 함수를 만들었습니다.
- NotifyPlaceInfo.kt : 기존의 GetPlaceInfo.kt 의 기능을 옮겼습니다.
- GetPlaceInfo.kt : 장소 ID와 함께 호출 시 Place 정보를 Place 라는 객체로 리턴할 수 있도록 구현했습니다.
- Place.kt : 장소 정보를 담을 수 있는 클래스를 선언하였습니다.

[HyeonJun] SurroundPlaceActivity 뼈대 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/SurroundPlaceActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt

- RetrofitService.kt : 필요한 API들의 동작을 기본적으로 기술하였습니다.
- History.kt : 사용자의 장소 방문로그를 위한 클래스를 만들었습니다. (ArrayList<History> 형태로 보여질 예정)
- User.kt : 사용자의 정보를 담을 클래스를 만들었습니다.

[HyeonJun] RetrofitService.kt API 세분화 구현

---

Web/Project_Footprint/website/templates/history_create.html
Web/Project_Footprint/website/templates/history_delete.html
Web/Project_Footprint/website/templates/history_list.html
Web/Project_Footprint/website/urls.py
Web/Project_Footprint/website/views.py

- website/urls.py : 히스토리 삭제 페이지 연결했습니다.
- website/views.py : 히스토리 생성,삭제 및 history 리스트를 보여주는 함수 수정했습니다.
- website/history_crete.html: 히스토리 생성 페이지 구현했습니다.
- website/history_delete.html: 히스토리 삭제
- website/history_list.html: 히스토리 목록 페이지 수정했습니다.
검토 바랍니당.

[YulHee] 임의의 History 생성 및 삭제기능 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/SurroundPlaceActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/NoticeFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_blank.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml
Application/Project_Footprint/app/src/main/res/navigation/mobile_navigation.xml
Application/Project_Footprint/app/src/main/res/values/strings.xml

- ForegroundService.kt : 비콘과 50미터 이하로 가까워지면 Notify를, 5미터 이하로 가까워지면 History POST 동작을 하게끔 구현했습니다.
- History.kt : 멤버 변수를 추가하였습니다.

[HyeonJun] ForegroundService 거리 비례 동작 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/SurroundPlaceActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/NaverPlaceID.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ShowPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- ForegroundService.kt : 주변에 특정 비콘이 가까워지면 해당 장소의 정보가 뜨도록 구현했습니다.
- RetrofitService.kt : 비콘이 설치된 장소의 Naver Place ID를 얻기 위한 API를 등록했습니다.
- NaverPlaceID.kt : 위 API의 응답을 받아올 데이터 클래스르 정의했습니다.
- ShowPlaceInfo.kt : Naver Place 페이지의 HTML 태그를 분석하여 Parser를 리팩토링했습니다.

[HyeonJun] ForegroundService에서 주변 비콘 감지 구현

---

Web/Project_Footprint/website/views.py

- views.py : History, Place title 부분 검색기능 추가, History 날짜 기간별 조회 기능 추가 구현했습니다.

[yewon] History, Place Titlte get Api 구현했습니다.

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/SurroundPlaceActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- ForegroundService.kt : 정기적으로 주변 Beacon 리스트를 Broadcasting 합니다.
- SurroundFragment.kt : 정기적으로 ForegroundService.kt의 데이터를 수신함으로써 RecyclerView를 갱신하도록 수정하였습니다.
- AndroidManifest.xml : Broadcast Receive 등록 코드를 추가하였습니다.

[HyeonJun] ForegroundService Broadcast 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- SurroundFragment.kt : AsyncTask를 통해 비동기적으로 데이터 리스트를 바인딩하도록 구현했습니다.

[HyeonJun] SurroundFragment AsyncTask 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- SurroundFragment.kt : ForegroundService.kt 에서 Braodcasting 하는 데이터를 바인딩하여 안정적으로 리스트화 하도록 구현했습니다.

[HyeonJun] SurroundFragment RecyclerView 구현 완료

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/res/layout/place_item.xml

- SurroundFragment.kt : 데이터가 변하지 않으면 AsyncTask를 실행하지 않도록 하여 최적화하였습니다.
- place_item.xml : 아이템 디자인을 수정하였습니다.

[HyeonJun] SurroundFragment 일부 수정

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ShowPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_surround.xml

- SurroundFragment.kt : 주변 장소 아이템을 누르면 해당 장소의 정보를 자세히 보여주는 페이지로 이동하는 기능을 구현했습니다. 또한 리스트를 동기화할 때마다 로딩 애니메이션을 보여줍니다.
- ShowPlaceInfo.kt : 반복되는 네트워킹 작업을 줄여 작업 속도를 최적화하였습니다.
- fragment_surround.xml : 로딩 애니메이션을 위한 ProgressBar 를 넣었습니다.

[HyeonJun] SurroundFragment 클릭 이벤트, 로딩 스플래시 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- SurroundFragment.kt : 주변에 여러 비콘이 있어도 정상 동작하게끔 로직을 변경하였습니다. 또한 중복 비콘 감지 처리를 위한 동작도 추가하였습니다.

[HyeonJun] SurroundFragment 여러 비콘 대응

---

Web/Project_Footprint/footprint/settings.py
Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/place_id_serializers.py
Web/Project_Footprint/website/views.py
Web/Project_Footprint/website/viewsets.py

- viewseyts.py : Place beacon uuid filter 기능 수정해서 추가했습니다.

[yewon] Place Api 수정

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- SurroundFragment.kt : 거리 순으로 순서가 바뀌기 때문에 새로운 데이터로 인식하는 버그가 있었는데, Set으로 변환하여 비교하는 방식으로 변경하여 해당 문제를 해결했습니다.
- ForegroundService.kt :
1) 비콘이 감지될 때 for-loop를 돌며 리스트를 완성하고 Broadcast 해야하는데 그렇지않아서 SurroundFragment 에서 비정상적인 동작을 하던 오류를 수정했습니다. (for-loop가 종료되고 Broadcasting 하도록 구현)
2) 새로운 비콘이 감지되면 Notification를 중복하여 발생하는 버그가 있었음. 비동기 처리 중 중복 처리가 이루어져 정상적으로 동작하지 않음을 확인하여 비동기 처리 이후 중복 스캔 처리를 하여 수정했습니다.

[HyeonJun] 중요 Bug Fix

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Login.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml

- LoginActivity.kt :
1) Django REST Login API에 대응하여 사용자의 이메일, 패스워드 값이 서버에 저장되어 있다면 HomeActivity로 전환되도록 구현했습니다.
2) SharedPreferences를 통하여 자동 로그인 기능을 구현했습니다.
- HomeFragment.kt : 로그인 요청의 응답으로 User Profile이 오기 때문에 홈 화면에 사용자의 닉네임을 띄우도록 하였습니다.
- User.kt : Login 요청의 Response 형태로 재구성하였습니다.
- Login.kt : 삭제하였습니다.

[HyeonJun] Login API 대응 및 자동 로그인 기능 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- Website.kt : BaseURL을 정적으로 보관하는 클래스를 생성하여 불편함을 덜었습니다.

[HyeonJun] Website BaseURL 데이터 클래스 생성

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/UpdateProfile.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/menu/MenuFragment.kt
Application/Project_Footprint/app/src/main/res/drawable/image_border.xml
Application/Project_Footprint/app/src/main/res/layout/activity_place_detail.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_edit_profile.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml
Application/Project_Footprint/app/src/main/res/navigation/mobile_navigation.xml
Application/Project_Footprint/app/src/main/res/values/styles.xml

- LoginActivity.kt : 사용자의 생년월일의 포맷이 맞지 않던 버그를 수정하였습니다. (Class Member Type 변경 : String -> Date)
- RetrofitService.kt : 회원 정보 변경 Function을 추가하였습니다.
- UpdateProfile.kt : 회원 정보 변경 API를 대응하기 위한 Body Class를 작성하였습니다.
- EditProfileFragment.kt : 회원 정보를 변경할 수 있도록 구현했습니다.
- fragment_edit_profile.xml : 회원 정보를 변경할 수 있는 UI를 설계하고 구현했습니다.

[HyeonJun] 회원 정보 변경 API 대응, Bug Fix

---

Web/Project_Footprint/website/admin.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/notice.html
Web/Project_Footprint/website/templates/notice_view.html
Web/Project_Footprint/website/urls.py
Web/Project_Footprint/website/views.py

- admin.py : Notice 모델 admin에 추가했습니다.
- models.py : Notice model 구현했습니다.
- urls.py : Notice list, Notice detail view url 추가했습니다.
- base.html : Notice 버튼 추가했습니다.
- notice.html : notice 목록 기본 구현했습니다.
- notice_view.html : notice 상세보기 기본 구현했습니다.

[yewon] 공지사항 페이지 기본 구현했습니다.

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/menu/MenuFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_edit_profile.xml

- EditProfileFragment.kt : Android-image-cropper 라이브러리와 SharedPreferences를 활용하여 프로필 사진 등록 및 변경 기능을 구현하였습니다.
- HomeFragment.kt : 프로필 사진 영역에 등록 및 변경한 프로필 사진이 보이도록 구현하고, 터치 시 메뉴 Fragment로 이동하는 동작을 구현했습니다.
- MenuFragment.kt :  프로필 사진 영역에 등록 및 변경한 프로필 사진이 보이도록 구현하였습니다.

[HyeonJun] 프로필 사진 등록 및 변경 기능 추가

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/WithdrawActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_withdraw.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_edit_profile.xml

- WithdrawActivity.kt : 비밀번호가 일치하면 서버에서 사용자의 정보를 삭제하도록 구현했습니다.
- activity_withdraw.xml : 비밀번호를 입력하기 위한 UI를 제작하였습니다.
- RetrofitService.kt : 회원 탈퇴를 위한 API를 대응하였습니다.

[HyeonJun] 회원 탈퇴 API 대응

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/WithdrawActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/res/menu/profile_image_menu.xml
Web/Project_Footprint/.idea/Project_Footprint.iml
Web/Project_Footprint/.idea/misc.xml
Web/Project_Footprint/.idea/workspace.xml
Web/Project_Footprint/footprint/settings.py

- EditProfileFragment.kt : Popup 메뉴를 추가하여 기본 이미지로 변경할 것인지, 사용자가 추가하는 이미지로 변경할 것인지 물어봅니다.

[HyeonJun] 프로필 변경 메뉴 추가

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_edit_profile.xml

- EditProfileFragment.kt : 로그아웃 기능을 구현했습니다. 사용자 정보와 로그인 정보가 모두 삭제되면서 로그인 화면으로 인텐트됩니다.

[HyeonJun] 로그아웃 기능 추가

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/notice_serializers.py
Web/Project_Footprint/website/viewsets.py

- urls.py : Notice list get Api url 을 추가했습니다.
- viewsets.py : Notice list get Api ViewSet 구현했습니다.
- notice_serializers.py : Notice Api Serializers 기능 구현했습니다.

[yewon] Notice list get Api 구현했습니다.

---

Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/viewsets.py

-website/models.py : place 모델 수정
-website/viewsets.py: 함수 제거 및 변경

[YulHee] place pk 변경

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/history_list.html

-website/forms.py :  모델 필드에 맞게 폼 변경
-website/models.py : custom_place 필드 추가
-website/templates/history_list.html: custom_place 추가

[YulHee] 임의 히스토리 구현했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/SurroundPlaceActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/WithdrawActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Login.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ShowPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_home.xml

- RetrofitService.kt : History Create API에 대응하는 메소드를 만들었습니다.
- ShowPlaceInfo.kt : 방문한 장소인지 지나가는 장소인지 구분하여 다른 푸시알림을 전송합니다.
- fragment_dashboard.xml : History를 조회할 수 있는 페이지의 UI를 추가했습니다.
- ForegroundService.kt : 특정 장소를 방문했을 때 History를 생성하고 Notify를 생성하는 기능을 구현했습니다.

[HyeonJun] History 생성 API 대응 및 UI 추가

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/viewsets.py

- urls.py : 객체 응답을 위한 url을 추가했습니다.
- viewsets.py : 객체 하나만 응답으로 return 하는 class 구현했습니다.

[yewon] Place Id get Api 배열에서 객체 응답으로 구현했습니다.

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/WithdrawActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Data/NaverPlaceID.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/NaverPlaceID.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/Place.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/UpdateProfile.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/GetPlaceTitleOnly.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ShowPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/edit_profile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/menu/MenuFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/notice/NoticeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/whole_history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_blank.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_whole_history.xml
Application/Project_Footprint/app/src/main/res/navigation/mobile_navigation.xml

- GetPlaceTitleOnly.kt : History 객체 내에는 Naver Place ID가 있는데, 기존 GetPlaceInfo.kt는 모든 정보를 갖고오기 때문에 비효율 적이었습니다. 따라서 Place의 Title만 가져와 History RecyclerView에 보여주기 위해 보다 효율적인 네트워킹 쓰레드를 구현하였습니다.
- 이외 디렉토리 생성 및 이동 등의 리팩토링을 하였습니다.

[HyeonJun] Naver Place ID를 통해 Place Title을 얻는 메소드 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- WholeHistoryFragment.kt : 이제 사용자의 히스토리만 조회되도록 변경하였습니다.

[HyeonJun] History 조회 API 오류 대응

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/viewsets.py

- viewsets.py : Place title filter 와 Place beacon_uuid filter 기능을 ApiPlaceId 하나의 함수로 중복 정리했습니다.

[yewon] Place get Api 중복 정리했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/ResponseInterceptor.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/dashboard/DashboardFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/KeywordHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/res/drawable/ic_baseline_search_24.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_date_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_keyword_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_today_history.xml
Application/Project_Footprint/app/src/main/res/navigation/mobile_navigation.xml

- History 조회 관련 : 어떤 Query이든 동일한 값이 조회되는 현상을 수정하였습니다.
- KeywordHistoryFragment.kt : 특정 키워드를 통해 사용자가 원하는 히스토리를 찾을 수 있습니다.

[HyeonJun] History 조회 관련 오류 수정, KeywordHistoryFragment 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_date_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_keyword_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_today_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_whole_history.xml

- DateHistoryFragment.kt : 사용자가 선택한 날짜의 History가 뜨도록 구현 하였습니다.

[HyeonJun] DateHistoryFragment 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_date_history.xml
Application/Project_Footprint/app/src/main/res/layout/history_item.xml

- DateHistoryFragment.kt : 애니메이션을 통해 CalendarView 가 상황에 따라 보여지고 안보여짐으로써 원활한 UX를 제공하도록 변경하였습니다.

[HyeonJun] DateHistoryFragment Expandable CardView 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml
Application/Project_Footprint/app/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
Application/Project_Footprint/app/src/main/res/layout/activity_history_detail.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_date_history.xml

- fragment_date_history.xml : CardView 상태에 대한 직관적인 인식을 위해 상태를 나타내는 ImageView를 추가했습니다.
- DateHistoryFragment.kt : CardView의 상태에 따라 ImageView의 Resource가 변화하도록 구현했습니다.

[HyeonJun] DateHistoryFragment Expandable CardView 일부 수정

---

Web/Project_Footprint/website/admin.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/index.html
Web/Project_Footprint/website/views.py

- views.py : Hot Place 리스트를 메인페이지에 넣기 위해 place  값을 받도록 수정했습니다.
- index.html : 메인페이지에 Hot Place 리스트 슬라이드를 구현했습니다.
- admin.py, models.py : count,img 를 위한 Place 모델 내용을 추가했습니다.

[yewon] Hot Place 슬라이드 프론트엔드 기본 구현했습니다.

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/VisitedPlace.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/build.gradle

- ForegroundService.kt : 관계형 데이터베이스 Realm 라이브러리를 활용하여 지나가거나 방문한 장소의 Naver Place ID를 로컬에 저장하여 추후 재활용될 때 네트워크 작업을 줄여주는 최적화 작업을 했습니다.

[HyeonJun] 최적화 - Realm 로컬 데이터베이스를 도입하여 장소 정보 저장

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/res/drawable/ic_baseline_check_24.xml
Application/Project_Footprint/app/src/main/res/layout/activity_history_detail.xml
Application/Project_Footprint/app/src/main/res/layout/activity_history_edit.xml
Application/Project_Footprint/app/src/main/res/menu/history_menu.xml
Application/Project_Footprint/app/src/main/res/values/mood_list.xml

- HistoryDetailActivity.kt : 사용자가 편집화면으로 이동했을 때, 기존의 내용을 보여주도록 Intent 데이터를 담습니다.
- HistoryEditActivity.kt : Intent 데이터를 기반으로 화면을 구성하고, 사용자의 기분 입력을 위해 스피너 메뉴를 구현했습니다.
- activity_history_edit.xml : 사용자의 입력을 받는 레이아웃으로 변경하였습니다.

[HyeonJun] HistoryEditActivity 구현

---

Web/Project_Footprint/website/admin.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/index.html
Web/Project_Footprint/website/templates/place_detail.html
Web/Project_Footprint/website/templates/place_list.html
Web/Project_Footprint/website/urls.py
Web/Project_Footprint/website/views.py

- admin.py : 관리자 페이지, Place 모델의 count instance 추가했습니다.
- models.py : 히스토리 생성시 place모델의 count 값을 증가할 수 있도록 함수 구현했습니다.
- urls.py : place-detail 페이지 간단 구현했습니다.
- views.py : Hot Place 슬라이드에 표시될 장소를 ordering 해줬습니다.

[yewon] Hot Places Count Instance 생성, Count 기준으로 핫플레이스 선정하기 구현했습니다.

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/viewsets.py

- viewsets.py : Hot Places 리스트 5개 가져오는 API 구현했습니다.
- urls.py :  Hot Places Api url 추가했습니다.

[yewon] Hot Places Get Api 구현했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/RegisterActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt

- RegisterActivity.kt : 입력 폼의 유효성을 검사한 뒤 회원 가입 Request를 보내는 동작을 구현했습니다.
- RegisterConfirmActivity.kt : 가입 후, 이메일 인증을 유도하는 화면을 구현했습니다.
- RetrofitService.kt : 회원가입 Request API를 대응했습니다.
- activity_register.xml : 회원가입 UI를 구현했습니다.

[HyeonJun] RegisterActivity 유효성 검사 및 API 대응

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/User.kt

- LoginActivity.kt : 회원가입 후 이메일을 인증하지 않으면 로그인이 되지 않도록 구현했습니다. 또한 이메일 및 비밀번호가 서버 정보와 일치하지 않을 때 로그인이 되지 않도록 구현했습니다.

[HyeonJun] LoginActivity 회원가입 관련 절차 대응

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/PasswordResetActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_login.xml
Application/Project_Footprint/app/src/main/res/layout/activity_password_reset.xml

- PasswordResetActivity.kt : 비밀번호 변경 API를 대응했으며, 가입된 사용자의 이메일을 통해 비밀번호 초기화 링크를 보내도록 구현했습니다.
- activity_password_reset.xml : 비밀번호 변경 링크를 보내기 위한 UI를 구현했습니다.
- activity_login.xml : 비밀번호 변경 페이지로 이동하기 위한 Intent를 설정했습니다.

[HyeonJun] PasswordResetActivity 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_login.xml
Application/Project_Footprint/app/src/main/res/layout/activity_password_reset.xml

- HistoryDetailActivity.kt : 히스토리 메뉴에서 '삭제하기'를 선택하면 해당 히스토리가 삭제되도록 구현했습니다.
- RetrofitService.kt : 히스토리 삭제 API를 대응했습니다.
- activity_login.xml : 비밀번호 변경 페이지로 이동하는 버튼이 잘 눌리지 않아 약간의 UI 수정을 했습니다.

[HyeonJun] History Delete API 대응 및 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/KeywordHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_history_detail.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_whole_history.xml

- History 조회 관련 Fragment : HistoryDetailActivity로 이동하여 HistoryEdit 메뉴를 선택하여 내용 수정을 한 뒤, 다시 History 조회 관련 Fragment로 이동했을 때 데이터가 정적이었던 문제를 해결하기위하여 onResume()에서 데이터를 다시 동기화하는 작업을 추가했습니다.

[HyeonJun] History 조회 관련 메뉴 Bug Fix

---

Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/History.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/DateHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/KeywordHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_history_write.xml
Application/Project_Footprint/app/src/main/res/layout/activity_home.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_edit_profile.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_today_history.xml

- HistoryWriteActivity.kt : 임의 히스토리 작성 Activity 입니다.
- activity_history_write.xml : 사용자 임의로 히스토리를 작성할 수 있는 페이지의 UI를 구현했습니다.
- activity_history_edit.xml : 임의 히스토리 작성 페이지와 디자인 통일감을 주기 위해 일부 수정하였습니다.
- activity_home.xml : Fragment 위치를 일부 조정하였습니다.

[HyeonJun] HistoryWriteActivity 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/res/layout/activity_history_detail.xml

- HistoryListAdapter.kt : 서버에 업로드되어있는 이미지를 로드하여 RecyclerView에 보여주는 기능을 구현했습니다.
* 이미지가 있는 히스토리를 수정할 시 400 Bad Request가 뜨는 현상 수정 예정

[HyeonJun] HistoryListAdapter 이미지 로드 구현

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/templates/signin.html
Web/Project_Footprint/website/templates/signup.html

[jinsol] : front/signup 구현

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/views.py
Web/Project_Footprint/website/viewsets.py

- website/forms.py : 폼 수정
- website/models.py : 모델 수정
- website/views.py : History 함수 수정
- website/viewset.py : 조회 api 수정

[YulHee] History create_at 필드 관련 기능 수정했습니다.

---

Application/Project_Footprint/app/build.gradle
Application/Project_Footprint/app/src/main/AndroidManifest.xml
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/UpdateHistory.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/UpdateHistoryNoImage.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/res/values/strings.xml
Application/Project_Footprint/build.gradle

- HistoryEditActivity.kt : 히스토리 이미지를 업로드할 수 있도록 구현했습니다
- UpdateHistory.kt : 이미지를 분리하여 MultiPart로 구현하도록 했습니다
- RetrofitService.kt : MultiPart Body를 전송하도록 수정하였습니다

[HyeonJun] History 이미지 업로드 구현

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt

- HistoryEditActivity.kt : 이미지를 수정했을 시 intent 데이터로 이미지 URI를 넘기도록 수정했습니다.
- HistoryDetailActivity.kt : 기존에 이미지를 수정해도 인텐트가 되면 수정된 결과가 보이지 않던 오류를 해결했습니다.

[HyeonJun] 이미지 업로드 시 발생하는 오류 해걸

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/history_list.html
Web/Project_Footprint/website/views.py

- website/forms.py : forms에 유저 수정 제외 구현
- website/veiws.py: history 함수 수정
- website/templates/base.html : css 수정
- website/templates/history_list: css 수정

[YulHee] history form 로그인 유저 자동생성 구현했습니다.

---

Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/myinfo.html
Web/Project_Footprint/website/templates/signin.html
Web/Project_Footprint/website/templates/signup.html

[jinsol] : front/회원정보조회

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/WriteHistory.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/res/layout/activity_history_write.xml

- RetrofitService.kt : 히스토리 편집과 마찬가지로 이미지 업로드 상황, 미 업로드 상황을 따로 구분하여 메소드를 작성하였습니다.
- HistoryWriteActivity.kt : 히스토리 업로드 시 이미지를 첨부할 수 있도록 구현했습니다.

[HyeonJun] HistoryWriteActivity 이미지 업로드 구현

---

Web/Project_Footprint/footprint/settings.py
Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/admin.py
Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/static/css/skel.css
Web/Project_Footprint/website/static/css/style.css
Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/editor.html
Web/Project_Footprint/website/templates/editor_view.html
Web/Project_Footprint/website/templates/notice.html
Web/Project_Footprint/website/templates/notice_view.html

- settings.py, urls.py, admin.py, forms.py, models.py : Editor Post 이미지 다중업로드 구현을 위해 ckeditor 를 추가했습니다.
- style.css : nav 상단바 위치 고정 수정했습니다.

[yewon] Editor post 이미지 파일 다중 업로드 구현, Base 상단바 수정 했습니다.

---

Web/Project_Footprint/website/templates/myinfo.html
Web/Project_Footprint/website/templates/user_delete.html
Web/Project_Footprint/website/templates/user_info_update.html
Web/Project_Footprint/website/views.py

[jinsol] : front/회원정보 조회,수정,삭제 구현

---

Web/Project_Footprint/website/history_serializer.py
Web/Project_Footprint/website/templates/history_list.html
Web/Project_Footprint/website/viewsets.py

-history_serializer.py: serializer 생성
-viewsets.py: update api 수정

[YulHee] History Update Api 수정했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Adapter/HistoryListAdapter.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/dashboard/DashboardFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/KeywordHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/WholeHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/activity_history_detail.xml
Application/Project_Footprint/app/src/main/res/layout/activity_history_write.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_today_history.xml
Application/Project_Footprint/app/src/main/res/layout/fragment_whole_history.xml
Application/Project_Footprint/app/src/main/res/values/mood_list.xml

- WholeHistoryFragment.kt : 불필요한 기능이라 판단되어 기능 삭제 조치 하였습니다.
- 이외 기타 버그 수정하였습니다.

[HyeonJun] WholeHistoryFragment 기능 삭제 및 기타 Bug Fix

---

Web/Project_Footprint/website/templates/base.html
Web/Project_Footprint/website/templates/editor.html
Web/Project_Footprint/website/templates/editor_view.html
Web/Project_Footprint/website/templates/index.html
Web/Project_Footprint/website/templates/notice.html
Web/Project_Footprint/website/templates/notice_view.html

- base.html : nav bar 수정했습니다.
- editor.html, editor_view.html, notice.html, notice_view.html : Notice, Editor 프론트엔드 카드 형식으로 수정 구현했습니다.
- index.html : 배경색 변경했습니다.

[yewon] Notice, Editor 프론트엔드 카드 형식으로 수정했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/WriteHistory.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt

- HistoryWriteActivity.kt : Django 모델 상으로 create_at을 auto_add = false를 한 이후 이미지와 함께 사용자 임의 히스토리 생성을 하면 오류가 발생하는 현상을 해결했습니다. LocalDateTime Format이 올바르지 않아 발생했던 문제였습니다.

[HyeonJun] History 생성 관련 Bug Fix

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/templates/index.html
Web/Project_Footprint/website/viewsets.py

- urls.py : Editor api url 추가 했습니다.
- viewsets.py :  Editor get Api 구현했습니다.
- index.html : background-color 수정했습니다.

[yewon] Editor get Api 구현했습니다.

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/history_list.html
Web/Project_Footprint/website/views.py

-website/views.py: history_create 함수 수정
-website/forms.py: form 수정
-website/models.py: 모델 수정
-website/history_list.html: css 코드 정리

[YulHee] : created_at필드 빈 폼일시 현재 시간으로 자동생성 구현했습니다.

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/history_create.html
Web/Project_Footprint/website/templates/history_update.html
Web/Project_Footprint/website/views.py

-website/models.py: 모델 필드 수정
-website/forms.py: mood 초이스필드 수정
-views.py: history_update 함수 수정
-history_create.html: 버튼 수정
-history_update.html: 페이지 수정

[YulHee] History 수정할 시 기존 내용 폼에 가지고 오기 구현했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- HomeFragment.kt : 발자취 따라가기 스위치의 상태를 관찰하는 LiveData를 포함하는 ViewModel에 상태를 게시하도록 구현했습니다.
- SurroundFragment.kt : ViewModel의 데이터에 따라 (스위치의 상태에 따라) RecyclerView 어댑팅 여부를 결정하도록 구현했습니다.

[HyeonJun] LiveData를 활용하여 Switch State에 따른 SurroundFragment 활성화 여부 결정 구현

---

Web/Project_Footprint/website/templates/user_info_update.html
Web/Project_Footprint/website/templates/user_password_update.html

[jinsol] : front/password_update 구현

---

Web/Project_Footprint/website/history_serializer.py
Web/Project_Footprint/website/viewsets.py

- history_serializer.py : serializer 수정
- history_viewset.py : 날짜순 정렬 수정

[YulHee] history 조회 API 수정했습니다.

---

Web/Project_Footprint/website/history_serializer.py
Web/Project_Footprint/website/viewsets.py

-history_serializer.py : 직렬화 함수 수정하여 시간,mood 자동생성 구현

[YulHee] history 자동생성 에러 수정했습니다.

---

Web/Project_Footprint/footprint/urls.py
Web/Project_Footprint/website/history_serializer.py
Web/Project_Footprint/website/templates/history_list.html

-history_serializer.py : put할 때, created_at도 수정가능하게 변경 및 mood 또는 created_at 필드 값 없을 경우 자동생성기능 추가

History list

---

Web/Project_Footprint/website/templates/password_email_confirm.html
Web/Project_Footprint/website/templates/password_reset.html
Web/Project_Footprint/website/templates/password_reset_complete.html
Web/Project_Footprint/website/templates/user_password_find.html

[jinsol] : 패스워드 초기화 구현

---

Web/Project_Footprint/website/hotplace_serializers.py
Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/place_detail.html
Web/Project_Footprint/website/views.py

- views.py : HotPlace 크롤링한 데이터를 Mysql DB에 저장하는 함수 구현 했습니다.

[yewon] HotPlace Mysql DB 연동 작업 구현했습니다.

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_dashboard.xml

- HomeFragment.kt : 사용자 조작으로 인한 화면 전환 시에 뷰 페이저의 자동 전환 Timer의 상태가 정상적이지 않아 오류가 발생하는 현상을 해결했습니다. 또한 HotPlaces API가 변경되어 대응 수정했습니다.
- RetrofitService.kt : HotPlaces API의 URL을 변경하였습니다.

[HyeonJun] ViewPager Timer Bug Fix 및 HotPlaces API 수정 대응

---

Web/Project_Footprint/website/models.py
Web/Project_Footprint/website/templates/history_list.html
Web/Project_Footprint/website/views.py

-views.py: 로그인 안했을 경우 로그인 페이지 전달
-models.py: jsonfield 임포트
-history_list.html: 수정

[YulHee] History url로 접근할때, 로그인 안했을 경우 로그인창 띄우기

---

Web/Project_Footprint/website/templates/history_list.html

[YulHee] History front-end수정했습니다.

---

Web/Project_Footprint/website/forms.py
Web/Project_Footprint/website/templates/myinfo.html
Web/Project_Footprint/website/templates/password_email_confirm.html
Web/Project_Footprint/website/templates/password_reset.html
Web/Project_Footprint/website/templates/password_reset_complete.html
Web/Project_Footprint/website/templates/user_delete.html
Web/Project_Footprint/website/templates/user_info_update.html
Web/Project_Footprint/website/templates/user_password_find.html
Web/Project_Footprint/website/templates/user_password_update.html
Web/Project_Footprint/website/views.py

[jinsol] : 반응형 구현

---

Web/Project_Footprint/website/history_serializer.py
Web/Project_Footprint/website/views.py

-views.py: History 관련 함수 주석 달았습니다.
-history_serializer.py: History 시리얼라이저 관련 함수 주석 달았습니다.

[YulHee] History model 관련 함수 주석달기

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/surround/SurroundFragment.kt

- HistoryDetailActivity.kt : 인스타그램 정책 상 이미지만 Intent 가 가능하기 때문에, 클립보드에 자동으로 피드에 담길 글을 작성해서 넣어주도록 구현했습니다.
- SurroundFragment.kt : ViewModel 상태를 잘못 인식하는 경우의 예외처리를 해주었습니다.

[HyeonJun] SNS 공유 시 Clipboard 에 본문 첨부 및 Bug Fix

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/ui/home/HomeFragment.kt
Web/Project_Footprint/.idea/workspace.xml
Web/Project_Footprint/footprint/settings.py
Web/Project_Footprint/website/views.py

- HistoryWriteActivity.kt : 사용자의 기분을 선택할 수 있도록 스피너 이벤트를 등록했습니다.- HistoryEditActivity.kt : 사용자의 기분을 선택할 수 있도록 스피너 이벤트를 등록했습니다.

[HyeonJun] History 작성 시 사용자 기분 입력 기능 구현

---

Web/Project_Footprint/website/models.py

[YulHee] history 오류 수정

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryWriteActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt

- HistoryWriteActivity.kt : 작성 시 사용자의 기분 (감정)을 입력받는 부분을 마저 구현했습니다.
- 이 외 기타 주석 보충을 하였습니다.

[HyeonJun] 주석 보충 및 미구현 부 구현 완료

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/EditorPickDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/res/layout/activity_editor_pick_detail.xml

- activity_editor_pick_detail.xml : 배너 부분은 스크롤이 적용되지 않아, 사용자에게 보여지는 콘텐츠 영역이 적은 문제가 있었어서 전체 레이아웃에 스크롤 뷰 적용함

[HyeonJun] Editor Pick 레이아웃 수정

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/home/HomeFragment.kt

- HomeFragment.kt : 자동으로 넘어가는 ViewPager 어댑터가 Handler 를 작동할 때 마다 ViewPager 객체가 Null 인지 검사하여 강제 종료 현상 해결함

[HyeonJun] View Pager NullPointerException 대응

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt

- ForegroundService.kt : 플래그 변수 (handlerStatus) 를 설정하여, 사용자가 Switch 를 ON/OFF 할 때 해당 플래그가 변경되도록 하고 Handler 에서 Empty Message 를 전송할 때 마다 해당 플래그 변수의 boolean 값을 참조하도록 함
ex) handlerStatus 가 False 일 때는 Handler 재 호출을 하지 않음 (Beacon 스캔을 하지 않음)

[HyeonJun] Beacon 스캔이 정상적으로 종료되지 않는 현상 해결

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/surround/SurroundFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/RetrofitService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ForegroundService.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/GetPlaceInfo.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Utility/ShowPlaceInfo.kt

- 값이 변하지 않는 변수에 대하여 val 사용을 지향하였고, Handler 동작 분리를 통해 가독성을 향상시켰습니다.

[HyeonJun] Clean Code

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt

- HistoryDetailActivity.kt : API 구조가 바뀌었기 때문에, 이를 대응하여 로직을 변경함

[HyeonJun] History에 사용자 입력 감정 표시되지 않던 오류 해결

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/history/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/res/layout/fragment_today_history.xml

- TodayHistoryFragment.kt : 마지막 남은 History 를 삭제할 때 앱이 강제 종료되는 현상을 해결하기 위해 RecyclerView 동작 방식을 변경하였습니다

[HyeonJun] TodayHistoryFragment.kt 마지막 History 삭제 시 강제종료 현상 해결

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/LoginActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/DataClass/User.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/EditProfile/EditProfileFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/History/TodayHistoryFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/Home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Network/Website.kt

- HistoryEditActivity.kt : 제목과 내용을 동시에 수정할 경우, API 호출 시 제목과 내용이 같은 값으로 들어갔던 오류를 수정했습니다.

[HyeonJun] History 수정 시 발생하는 오류 수정

---

Web/Project_Footprint/accounts/forms.py
Web/Project_Footprint/accounts/templates/signup.html

[jinsol] User 모델 birthdate 필드 수정

---

Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryDetailActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Activity/HistoryEditActivity.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/Home/HomeFragment.kt
Application/Project_Footprint/app/src/main/java/com/haerokim/project_footprint/Fragment/SurroundPlace/SurroundFragment.kt

- SurroundFragment.kt : ViewModel 의 상태를 관찰하도록 로직을 변경하였습니다.
- HomeFragment.kt : 스위치 상태를 ViewModel 에 저장하는 동작을 개선하였습니다.

[HyeonJun] SurroundFragment 가 ViewModel Observing 못하는 문제 해결

---

Web/Project_Footprint/accounts/forms.py

[jinsol] User 모델 birthdate 필드 수정2
